# Generated by Django 4.2.11 on 2024-05-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'todolist',
                'managed': False,
            },
        ),
    ]
